name: converse
description: "A simple chat app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10+1
  socket_io_client: ^3.0.0
  firebase_core: ^3.6.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  dio: ^5.4.3+1
  lottie: ^3.1.1
  intl: ^0.19.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.1.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  get_it: ^8.0.2
  dartz: ^0.10.1
  uuid: ^4.5.1
  flutter_slidable: ^3.1.1
  slider_button: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/pngs/app-icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/svgs/
    - assets/jsons/
