name: converse
description: "A simple chat app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.2.1
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10+1
  socket_io_client: ^2.0.3+1
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  uuid: ^4.4.0
  emoji_picker_flutter: ^2.2.0
  animated_text_kit: ^4.2.2
  animations: ^2.0.11
  image_picker: ^1.1.1
  firebase_storage: ^11.7.5
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  image_gallery_saver: ^2.0.3
  dio: ^5.4.3+1
  lottie: ^3.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/pngs/app-icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  background_image: assets/pngs/background.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/svgs/
    - assets/jsons/
